version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ticketbooking-db
    restart: always
    environment:
      MYSQL_DATABASE: ticket_booking
      MYSQL_ROOT_PASSWORD: Navdeep@9999
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ticketbooking-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-pNavdeep@9999",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ticketbooking-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ticket_booking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Navdeep@9999
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8808:8808"
    networks:
      - ticketbooking-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ticketbooking-frontend
    restart: always
    ports:
      - "8087:80"
    depends_on:
      - backend
    networks:
      - ticketbooking-net

volumes:
  db_data:

networks:
  ticketbooking-net:
    driver: bridge
