FROM node:18 AS build-stage
WORKDIR /app

COPY OnlineTicketBookingFrontend/package*.json ./
COPY OnlineTicketBookingFrontend/ ./

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY OnlineTicketBookingFrontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]